### ISSUE TITLE
Broken translations 'cause resolveBrowserLocale returns a locale not supported in messages object

### ISSUE THREAD

**Issue by mendozammatias** [RestUI/rest-ui#4]
Some translations in the example are broken.
For example, in Post Edit view.

**Comment by JonatanSalas** [comment]
I have figure out that error its related to the method **resolveBrowserLocale**. I have passed to the Admin component, a locale prop hardcoded with value **en** and it resolves the translations in a properly manner. 

We should review it more. But for now, I will update the references in the project to use a hardcode value, while I keep investigating for further details.

**Comment by JonatanSalas** [comment]
The problem was that we have an Object providing the userMessages definitions in the languages that we want to support. Using the method **resolveBrowserLocale** will behave as expected. In our case, that we are in Argentina, our browsers locale will resolve to **es** or **es-AR**. 

In the TranslationProvider component, the userMessages we pass to the Admin component gets accessed by the locale we have also passed to the Admin. Our object contains the following description: 

```javascript
const userMessages = {
     'en': {...},
     'fr': {...}
}
```
And when it tries to access in this way: 

```javascript
const messages = userMessages[locale] || {};
```

This way of accessing the object will result in {} being assigned to the messages variable, because locale value at runtime is 'es', and the 'es' key is not defined in the object. So, all of our custom messages will be lost.

**Comment by JonatanSalas** [comment]
We should take care of this situation, or make and advice in the console to the lib user, in order to make them fix this kind of issue faster, or document this in a troubleshooting readme.

**Comment by JonatanSalas** [comment]
As know the project has a dependency on react-i18n-polyglot which is our translations module, we don't have to track this issue here. I will create one issue in react-i18n-polyglot.
